testpython36:
  image: python:3.6
  script:
  - apt-get update -qy
  - pip install .
  - mkdir results
  - python -m unittest discover
  
testpython35:
  image: python:3.5
  script:
  - apt-get update -qy
  - pip install .
  - mkdir results
  - python -m unittest discover
  